version: '3'

services:
  # Define the Traefik service
  traefik:
    # Use the official Traefik v3.1 image
    image: traefik:v3.1
    # Command-line arguments for Traefik
    command:
      # Enable the Docker provider for Traefik
      - --providers.docker=true
      # Do not expose containers unless explicitly told so
      - --providers.docker.exposedbydefault=false
      # Define an entrypoint named 'web' listening on port 80
      - --entrypoints.web.address=:80
    # Map port 8001 on the host to port 80 in the container
    ports:
      - "8001:80"
    # Mount the Docker socket to allow Traefik to communicate with the Docker daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # Define the custom whoami service
  our_app:
    # Build the Docker image using the Dockerfile in the current directory
    build: .
    # Labels to configure Traefik routing
    labels:
      # Enable Traefik for this service
      - "traefik.enable=true"
      # Define the routing rule based on the 'Host' header
      - "traefik.http.routers.lastfm.rule=Host(`localhost`)"
      # Specify the entrypoint to use (must match the entrypoint defined in Traefik)
      - "traefik.http.routers.lastfm.entrypoints=web"
